---
# Create a Nginx server block to make a Monolith service available at its service port

- name: ensure service document root exists
  file:
    path="{{ monolith_core_monolith_service_root }}"
    owner="{{ monolith_core_monolith_service_non_privileged_user }}"
    group="{{ monolith_core_monolith_service_non_privileged_user }}"
    state=directory
  when: "'manager--vagrant' not in group_names"

- name: generate server block for service
  template:
    src="templates/etc/nginx/sites-available/monolith-service-server-block.j2"
    dest="/etc/nginx/sites-available/{{ monolith_core_monolith_service_name }}"
  notify: Restart Nginx

- name: enable service server block
  file:
      src="/etc/nginx/sites-available/{{ monolith_core_monolith_service_name }}"
     dest="/etc/nginx/sites-enabled/{{ monolith_core_monolith_service_name }}"
    state=link
  notify: Restart Nginx
