---
# Installs useful utilities for managing Monolith and Monolith services

- name: install utilities
  apt:
                 pkg={{ item }}
        update_cache=yes
    cache_valid_time=3600
               state=present
  with_items:
    - curl
    - htop
